version: '3.8'

services:
    app:
        image: myapp
        depends_on:
            - mysql
            - redis
        command: bash -c "service nginx start && uwsgi --ini /proj/app.ini"
        expose:
            - "443"
        ports:
            - "443:443"

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
        volumes:
            - "./db:/docker-entrypoint-initdb.d"
            
    redis:
        image: redis
            
